title: Cristina M. Conone
logo: /assets/img/headshot.png
description: Student of Supply Chain Analytics
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
